name: deployLambdaApi

on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
jobs: 
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-24.04
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2